updated line 28
signalapp/Signal-Server pull request #109
Opened 2021-01-09 23:18 UTC by Shakir101

just a beginner making trying out pull requests

2021-01-10 20:02 UTC, mahyuddin1359 reviewed
good

2021-01-11 00:02 UTC, mpires commented on gcm-sender-async/pom.xml
> +            <scope>tests</scope>
The proper maven scope here is actually test

2021-01-11 10:08 UTC, maks1m commented
> just a beginner making trying out pull requests

In this case I would recommend you to read https://chris.beams.io/posts/git-commit/

2021-01-11 13:57 UTC, ohbus requested changes
Please update yourself in these matters.

2021-01-12 08:23 UTC, JJS777 approved these changes

2021-01-12 08:27 UTC, JJS777 approved these changes

2021-01-12 08:27 UTC, JJS777 approved these changes

2021-01-23 15:21 UTC, Astrodevil approved these changes

2021-01-23 15:21 UTC, Astrodevil commented on gcm-sender-async/pom.xml
> +            <scope>tests</scope>
yeah here is the (test) please remove s from it. the scope is test not tests.

2021-04-07 21:21 UTC, closed without merging